name: 'slim_vendor_app_client'
version: 0.0.1
description: Client side of SlimView demo app
author: Daniel Varga-Hali <dvarga@skawa.hu>
homepage: https://www.easyling.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: '>=2.0.0-beta.17'
  browser: '>=0.10.0 <0.11.0'
  js: any
  slim_vendor_app_server:
    path: '../server'
  dart_slimlib:
    git:
      url: https://github.com/easyling/dart_slimlib
      ref: v0.0.2
  less_dart: '>=0.3.4'
transformers:
- less_dart:
    entry_points:
      - lib/components/*/*.less
- angular2:
    entry_points: web/main.dart
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'