name: 'slim_vendor_app'
version: 0.0.1
description: SlimView test and demo application
author: Daniel Varga <dvarga@skawa.hu>
homepage: https://www.easyling.com
dev_dependencies:
  test: "0.12.13+4"
  webdriver: any
  logging: ">=0.11.3"